version: '3'

volumes:
  postgres_data:

services:
  web:
    build:
      context: .
      args:
        RAILS_ENV: development
    image: samkillgallon/archery-tracker
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack_dev_server
      ARCHERY_DATABASE_HOST: 'postgres'
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached
    depends_on:
      - postgres
      - webpack_dev_server

  postgres:
    image: postgres:11.2
    volumes:
      - postgres_data:/var/lib/postgesql/data:cached

  webpack_dev_server:
    command: ./bin/webpack-dev-server
    build:
      context: .
      args:
        RAILS_ENV: development
    image: samkillgallon/archery-tracker
    environment:
      WEBPACKER_DEV_SERVER_HOST: '0.0.0.0'
    ports:
      - '8080:8080'
    volumes:
      - .:/app:cached
