version: '3'

volumes:
  mysql_data: {}

services:
  web:
    build:
      context: .
      args:
        RAILS_ENV: development
    image: samkillgallon/archery-tracker
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack_dev_server
    ports:
      - '3000:80'
    volumes:
      - .:/app:cached
    depends_on:
      - db
      - webpack_dev_server

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql:cached
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  webpack_dev_server:
    command: ./bin/webpack-dev-server
    build:
      context: .
      args:
        RAILS_ENV: development
    image: samkillgallon/archery-tracker
    environment:
      WEBPACKER_DEV_SERVER_HOST: '0.0.0.0'
    ports:
      - '8080:8080'
    volumes:
      - .:/app:cached
